<?php

namespace Display\CmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
    /**
     * @param int $id
     * @return Media
     */
    public function findById($id)
    {
        $dql = 'SELECT partial m.{id, name, path}
                FROM DisplayCmsBundle:Media m
                WHERE m.id = :id';
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameter('id', $id);

        return $query->getOneOrNullResult();
    }

    /**
     * @param string $mime
     * @return array
     */
    public function findByType($mime = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('m')
            ->from('DisplayCmsBundle:Media', 'm')
        ;

        if (null !== $mime) {
            $qb
                ->where('m.mime LIKE :mime')
                ->setParameter('mime', $mime. '%')
            ;
        }

        return $qb->getQuery()->getResult();
    }

    /**
     * @param array $ids
     * @return array
     */
    public function findByIds(array $ids)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('m')
            ->from('DisplayCmsBundle:Media', 'm')
            ->andWhere($qb->expr()->in('m.id', ':ids'))
            ->setParameter('ids', $ids)
        ;

        return $qb->getQuery()->getResult();
    }
}
