<?php

namespace Display\CmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function getList()
    {
        $dql = 'SELECT m
                FROM DisplayCmsBundle:Menu m
                JOIN m.page p
                GROUP BY p.locale
                ORDER BY m.updatedAt DESC';

        $query = $this->getEntityManager()->createQuery($dql);

        return $query->getResult();
    }

    /**
     * @param string $locale
     * @return array
     */
    public function findByLocale($locale)
    {
        $dql = 'SELECT m, p
                FROM DisplayCmsBundle:Menu m
                JOIN m.page p
                LEFT JOIN m.parent pr
                WHERE p.locale = :locale
                  AND pr.id IS NULL
                ORDER BY m.position ASC';

        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameter('locale', $locale);

        return $query->getResult();
    }
}
